# Generated by Django 4.0.5 on 2022-07-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0002_quiz_count_down'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='count_down',
        ),
        migrations.AddField(
            model_name='exam',
            name='count_down',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
