# Generated by Django 4.0.5 on 2022-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0003_remove_quiz_count_down_exam_count_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
