# Generated by Django 4.0.5 on 2022-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0005_quizuser_passed_exams_quizuser_point_score_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='quizzes_length',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
