# Generated by Django 4.0.5 on 2022-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0006_exam_quizzes_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
