# Generated by Django 4.0.5 on 2022-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0007_exam_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='email',
            field=models.EmailField(help_text='Enter your email', max_length=254),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
