# Generated by Django 4.0.5 on 2022-08-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0008_alter_quizuser_email_alter_quizuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
