# Generated by Django 4.0.5 on 2022-08-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0009_quiz_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='user_answer',
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='her.quizuser')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_answer',
            field=models.ManyToManyField(blank=True, null=True, to='her.useranswer'),
        ),
    ]
