# Generated by Django 4.0.5 on 2022-08-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0010_remove_quiz_user_answer_useranswer_quiz_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='user_answer',
            field=models.ManyToManyField(blank=True, to='her.useranswer'),
        ),
    ]
