# Generated by Django 4.1 on 2022-08-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('her', '0011_alter_quiz_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='her.exam')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='her.quiztype')),
                ('user_answer', models.ManyToManyField(blank=True, null=True, to='her.useranswer')),
            ],
        ),
        migrations.AlterField(
            model_name='editoruser',
            name='quizzes',
            field=models.ManyToManyField(blank=True, to='her.question'),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='her.question'),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
